//
// The middle source was generated by the Retargetable Decompiler
// Website: https://retdec.com
//
// The final source was generated by the UraniumVCPU Sampler Framework
// Website: http://yunyoo.cn
//

// Address range: 0x10000211c - 0x100003424
// Demangled:     do_main(int, char const**)
int64_t __Z7do_mainiPPKc(int32_t a1, char ** a2) {
    // 0x10000211c
    g111[0] = *(char *)&g105 ^ 35;
    g112[0] = *(char *)&g106 ^ -57;
    g113[0] = *(char *)&g107 ^ -47;
    g114[0] = *(char *)&g108 ^ -109;
    *(char *)&g115 = *(char *)&g109 ^ 109;
    *(char *)&g116 = *(char *)&g110 ^ -78;
    g148[0] = *(char *)&g117 ^ -22;
    g149[0] = *(char *)&g118 ^ 66;
    g150[0] = *(char *)&g119;
    g151[0] = *(char *)&g120 ^ -18;
    g152[0] = *(char *)&g121 ^ 96;
    g153[0] = *(char *)&g122 ^ -123;
    g154[0] = *(char *)&g123 ^ -121;
    g155[0] = *(char *)&g124 ^ 62;
    g156[0] = *(char *)&g125 ^ -75;
    g157[0] = *(char *)&g126 ^ -81;
    g158[0] = *(char *)&g127 ^ -64;
    g159[0] = *(char *)&g128 ^ 126;
    g160[0] = *(char *)&g129 ^ -77;
    g161[0] = *(char *)&g130 ^ 32;
    g162[0] = *(char *)&g131 ^ 22;
    g163[0] = *(char *)&g132 ^ -109;
    g164[0] = *(char *)&g133 ^ 52;
    g165[0] = *(char *)&g134 ^ -73;
    g166[0] = *(char *)&g135 ^ 22;
    g167[0] = *(char *)&g136 ^ 55;
    g168[0] = *(char *)&g137 ^ -16;
    g169[0] = *(char *)&g138 ^ 87;
    g170[0] = *(char *)&g139 ^ 115;
    g171[0] = *(char *)&g140 ^ -77;
    g172[0] = *(char *)&g141 ^ 44;
    g173[0] = *(char *)&g142 ^ -71;
    g174[0] = *(char *)&g143 ^ 118;
    g175[0] = *(char *)&g144 ^ -45;
    g176[0] = *(char *)&g145 ^ 15;
    g177[0] = -1 - *(char *)&g146;
    *(char *)&g178 = *(char *)&g147 ^ -119;
    *(char *)&g179 = 0;
    g100[0] = *(char *)&g95 ^ 86;
    g101[0] = *(char *)&g96 ^ -11;
    g102[0] = *(char *)&g97 ^ -56;
    *(char *)&g103 = *(char *)&g98 ^ 75;
    *(char *)&g104 = *(char *)&g99 ^ -51;
    g10[0] = *(char *)&g1 ^ 68;
    g11[0] = *(char *)&g2 ^ -43;
    g12[0] = *(char *)&g3 ^ 24;
    g13[0] = *(char *)&g4 ^ 101;
    g14[0] = *(char *)&g5 ^ -87;
    g15[0] = *(char *)&g6 ^ 54;
    g16[0] = *(char *)&g7 ^ 123;
    g17[0] = *(char *)&g8 ^ 26;
    g18[0] = *(char *)&g9 ^ -77;
    *(char *)&g19 = 71;
    *(char *)&g20 = 0;
    g58[0] = *(char *)&g21 ^ 19;
    g59[0] = *(char *)&g22 ^ -110;
    g60[0] = *(char *)&g23 ^ -78;
    g61[0] = *(char *)&g24 ^ 56;
    g62[0] = *(char *)&g25 ^ 118;
    g63[0] = *(char *)&g26 ^ 8;
    g64[0] = *(char *)&g27 ^ -32;
    g65[0] = *(char *)&g28 ^ 8;
    g66[0] = *(char *)&g29 ^ -93;
    g67[0] = *(char *)&g30 ^ 18;
    g68[0] = *(char *)&g31 ^ 94;
    g69[0] = *(char *)&g32 ^ 94;
    g70[0] = *(char *)&g33 ^ -34;
    g71[0] = *(char *)&g34 ^ -120;
    g72[0] = *(char *)&g35 ^ -78;
    g73[0] = *(char *)&g36 ^ 125;
    g74[0] = *(char *)&g37 ^ -64;
    g75[0] = *(char *)&g38 ^ 46;
    g76[0] = *(char *)&g39 ^ 13;
    g77[0] = *(char *)&g40 ^ 5;
    g78[0] = *(char *)&g41 ^ 85;
    g79[0] = *(char *)&g42 ^ 31;
    g80[0] = *(char *)&g43 ^ -113;
    g81[0] = *(char *)&g44 ^ -27;
    g82[0] = *(char *)&g45 ^ -93;
    g83[0] = *(char *)&g46 ^ -73;
    g84[0] = *(char *)&g47 ^ -23;
    g85[0] = *(char *)&g48 ^ 39;
    g86[0] = *(char *)&g49 ^ 74;
    g87[0] = *(char *)&g50 ^ -62;
    g88[0] = *(char *)&g51 ^ 7;
    g89[0] = *(char *)&g52 ^ -112;
    g90[0] = *(char *)&g53 ^ 122;
    g91[0] = *(char *)&g54 ^ -87;
    g92[0] = *(char *)&g55 ^ 40;
    *(char *)&g93 = *(char *)&g56 ^ -34;
    *(char *)&g94 = *(char *)&g57 ^ -38;
    __asm_stlr(1, (int64_t)g180);
    int64_t v1; // 0x10000211c
    int32_t v2 = v1; // 0x100003034
    int64_t v3; // bp-136, 0x10000211c
    *(int32_t *)&v3 = v2;
    int64_t v4 = _getenv(g10); // 0x100003040
    int64_t v5; // bp-168, 0x10000211c
    *(int32_t *)&v5 = 0;
    if (v2 != 0) {
        // 0x1000033c0
        return _puts((int64_t)&g148);
    }
    // 0x100003184
    int64_t v6; // bp-184, 0x10000211c
    int64_t v7 = &v6; // 0x100003028
    unsigned char v8 = (char)__ZL19am_I_being_debuggedv((int64_t *)v4) % 2; // 0x100003198
    *(char *)&v6 = v8;
    int64_t v9 = v8 == 0 ? (int64_t)&g111 : (int64_t)&g100; // 0x100003204
    *(int64_t *)(v7 - 8) = v9;
    *(int64_t *)(v7 - 16) = *(int64_t *)v1;
    _printf(g58);
    int64_t v10 = _sleep(2); // 0x1000032b8
    uint32_t v11 = *(int32_t *)&v5 + 1; // 0x10000335c
    *(int32_t *)&v5 = v11;
    while (v11 >= *(int32_t *)&v3) {
        // 0x100003184
        v8 = (char)__ZL19am_I_being_debuggedv((int64_t *)v10) % 2;
        *(char *)&v6 = v8;
        v9 = v8 == 0 ? (int64_t)&g111 : (int64_t)&g100;
        *(int64_t *)(v7 - 8) = v9;
        *(int64_t *)(v7 - 16) = *(int64_t *)v1;
        _printf(g58);
        v10 = _sleep(2);
        v11 = *(int32_t *)&v5 + 1;
        *(int32_t *)&v5 = v11;
    }
    // 0x1000033c0
    return _puts((int64_t)&g148);
}

