//
// The middle source was generated by the Retargetable Decompiler
// Website: https://retdec.com
//
// The final source was generated by the UraniumVCPU Sampler Framework
// Website: http://yunyoo.cn
//

// Address range: 0x10000211c - 0x100002184
// Demangled:     do_main(int, char const**)
int64_t __Z7do_mainiPPKc(int32_t a1, char ** a2) {
    // 0x10000211c
    int64_t result; // 0x10000211c
    return result;
}

// Address range: 0x100002188 - 0x100002f98
int64_t sub_100002188(void) {
    // 0x100002934
    int64_t v1; // 0x100002934
    int32_t * v2 = (int32_t *)(v1 - 104); // 0x100002934
    *v2 = (int32_t)v1;
    int32_t * v3 = (int32_t *)(v1 - 112); // 0x100002940
    *v3 = 0x570d5300;
    char * v4 = (char *)(v1 - 97); // 0x100002978
    *v4 = (char)(*v2 == 0);
    *v3 = -0x34c9b902;
    *v3 = *v4 % 2 == 0 ? -0x681ed8fa : -0x665b8cca;
    g111[0] = *(char *)&g105 ^ 35;
    g112[0] = *(char *)&g106 ^ -57;
    g113[0] = *(char *)&g107 ^ -47;
    g114[0] = *(char *)&g108 ^ -109;
    *(char *)&g115 = *(char *)&g109 ^ 109;
    *(char *)&g116 = *(char *)&g110 ^ -78;
    g148[0] = *(char *)&g117 ^ -22;
    g149[0] = *(char *)&g118 ^ 66;
    g150[0] = *(char *)&g119;
    g151[0] = *(char *)&g120 ^ -18;
    g152[0] = *(char *)&g121 ^ 96;
    g153[0] = *(char *)&g122 ^ -123;
    g154[0] = *(char *)&g123 ^ -121;
    g155[0] = *(char *)&g124 ^ 62;
    g156[0] = *(char *)&g125 ^ -75;
    g157[0] = *(char *)&g126 ^ -81;
    g158[0] = *(char *)&g127 ^ -64;
    g159[0] = *(char *)&g128 ^ 126;
    g160[0] = *(char *)&g129 ^ -77;
    g161[0] = *(char *)&g130 ^ 32;
    g162[0] = *(char *)&g131 ^ 22;
    *v3 = -0x618e444a;
    g163[0] = *(char *)&g132 ^ -109;
    g164[0] = *(char *)&g133 ^ 52;
    g165[0] = *(char *)&g134 ^ -73;
    g166[0] = *(char *)&g135 ^ 22;
    g167[0] = *(char *)&g136 ^ 55;
    g168[0] = *(char *)&g137 ^ -16;
    g169[0] = *(char *)&g138 ^ 87;
    g170[0] = *(char *)&g139 ^ 115;
    g171[0] = *(char *)&g140 ^ -77;
    g172[0] = *(char *)&g141 ^ 44;
    g173[0] = *(char *)&g142 ^ -71;
    g174[0] = *(char *)&g143 ^ 118;
    g175[0] = *(char *)&g144 ^ -45;
    g176[0] = *(char *)&g145 ^ 15;
    g177[0] = -1 - *(char *)&g146;
    *(char *)&g178 = *(char *)&g147 ^ -119;
    *v3 = -0x4b816a6a;
    *(char *)&g179 = 0;
    g100[0] = *(char *)&g95 ^ 86;
    g101[0] = *(char *)&g96 ^ -11;
    g102[0] = *(char *)&g97 ^ -56;
    *(char *)&g103 = *(char *)&g98 ^ 75;
    *(char *)&g104 = *(char *)&g99 ^ -51;
    g10[0] = *(char *)&g1 ^ 68;
    g11[0] = *(char *)&g2 ^ -43;
    g12[0] = *(char *)&g3 ^ 24;
    g13[0] = *(char *)&g4 ^ 101;
    g14[0] = *(char *)&g5 ^ -87;
    g15[0] = *(char *)&g6 ^ 54;
    g16[0] = *(char *)&g7 ^ 123;
    g17[0] = *(char *)&g8 ^ 26;
    g18[0] = *(char *)&g9 ^ -77;
    *(char *)&g19 = 71;
    *(char *)&g20 = 0;
    g58[0] = *(char *)&g21 ^ 19;
    g59[0] = *(char *)&g22 ^ -110;
    g60[0] = *(char *)&g23 ^ -78;
    g61[0] = *(char *)&g24 ^ 56;
    g62[0] = *(char *)&g25 ^ 118;
    g63[0] = *(char *)&g26 ^ 8;
    g64[0] = *(char *)&g27 ^ -32;
    g65[0] = *(char *)&g28 ^ 8;
    g66[0] = *(char *)&g29 ^ -93;
    g67[0] = *(char *)&g30 ^ 18;
    g68[0] = *(char *)&g31 ^ 94;
    g69[0] = *(char *)&g32 ^ 94;
    g70[0] = *(char *)&g33 ^ -34;
    g71[0] = *(char *)&g34 ^ -120;
    g72[0] = *(char *)&g35 ^ -78;
    g73[0] = *(char *)&g36 ^ 125;
    g74[0] = *(char *)&g37 ^ -64;
    g75[0] = *(char *)&g38 ^ 46;
    g76[0] = *(char *)&g39 ^ 13;
    g77[0] = *(char *)&g40 ^ 5;
    g78[0] = *(char *)&g41 ^ 85;
    g79[0] = *(char *)&g42 ^ 31;
    g80[0] = *(char *)&g43 ^ -113;
    g81[0] = *(char *)&g44 ^ -27;
    g82[0] = *(char *)&g45 ^ -93;
    g83[0] = *(char *)&g46 ^ -73;
    g84[0] = *(char *)&g47 ^ -23;
    g85[0] = *(char *)&g48 ^ 39;
    g86[0] = *(char *)&g49 ^ 74;
    g87[0] = *(char *)&g50 ^ -62;
    g88[0] = *(char *)&g51 ^ 7;
    g89[0] = *(char *)&g52 ^ -112;
    g90[0] = *(char *)&g53 ^ 122;
    g91[0] = *(char *)&g54 ^ -87;
    g92[0] = *(char *)&g55 ^ 40;
    *(char *)&g93 = *(char *)&g56 ^ -34;
    *(char *)&g94 = *(char *)&g57 ^ -38;
    *v3 = -0x3444c604;
    __asm_stlr(1, g180);
    return ___chkstk_darwin(93);
}

// Address range: 0x100002f98 - 0x100002fb4
int64_t sub_100002f98(void) {
    // 0x100003744
    int64_t v1; // bp-16, 0x100002f98
    int64_t v2; // 0x100003744
    *(int64_t *)(v2 - 96) = (int64_t)&v1;
    return ___chkstk_darwin(v2);
}

// Address range: 0x100002fb4 - 0x100003008
int64_t sub_100002fb4(void) {
    // 0x100003760
    int64_t v1; // bp-16, 0x100002fb4
    int64_t v2; // 0x100003760
    *(int64_t *)(v2 - 88) = (int64_t)&v1;
    *(int32_t *)(v2 - 112) = 0x480f9a38;
    return ___chkstk_darwin((int64_t)&g10);
}

// Address range: 0x100003008 - 0x100003024
int64_t sub_100003008(void) {
    // 0x1000037b4
    int64_t v1; // bp-16, 0x100003008
    int64_t v2; // 0x1000037b4
    *(int64_t *)(v2 - 80) = (int64_t)&v1;
    return ___chkstk_darwin(v2);
}

// Address range: 0x100003024 - 0x100003424
int64_t sub_100003024(void) {
    // 0x1000037d0
    int64_t v1; // bp-16, 0x100003024
    int64_t v2 = &v1; // 0x1000037d4
    int64_t v3; // 0x1000037d0
    int64_t * v4 = (int64_t *)(v3 - 72); // 0x1000037d8
    *v4 = v2;
    int64_t * v5 = (int64_t *)(v3 - 96); // 0x1000037dc
    *(int32_t *)*v5 = (int32_t)v3;
    int64_t v6 = _getenv(); // 0x1000037ec
    *(char *)(v3 - 57) = (char)(v6 != 0);
    int32_t * v7 = (int32_t *)(v3 - 112); // 0x100003808
    *v7 = -0x5e124203;
    int64_t * v8 = (int64_t *)(v3 - 80); // 0x1000038dc
    *(int32_t *)*v8 = 0;
    int32_t * v9 = (int32_t *)(v3 - 56); // 0x10000391c
    int32_t * v10 = (int32_t *)(v3 - 52); // 0x100003948
    int64_t * v11 = (int64_t *)(v3 - 48);
    char * v12 = (char *)(v3 - 34);
    int32_t * v13 = (int32_t *)(v3 - 32);
    int32_t * v14 = (int32_t *)(v3 - 28);
    int64_t v15 = v6; // 0x100003910
    *v7 = -0xf55d006;
    *v9 = *(int32_t *)*v8;
    *v7 = 0x783ec9c8;
    *v10 = *(int32_t *)*v5;
    *v7 = 0x6f19b2c;
    uint32_t v16 = *v9; // 0x10000396c
    uint32_t v17 = *v10; // 0x100003970
    int32_t v18 = v16 - v17; // 0x100003974
    *v7 = v18 < 0 == ((v18 ^ v16) & (v17 ^ v16)) < 0 ? 0x75d96b31 : -0x7d5f3e16;
    while (v16 >= v17) {
        // 0x100003994
        *v7 = 0x1d56b1ac;
        *(char *)*v4 = (char)__ZL19am_I_being_debuggedv((int64_t *)v15) % 2;
        *v11 = *(int64_t *)*(int64_t *)(v3 - 88);
        *v7 = -0x37e72274;
        unsigned char v19 = *(char *)*v4; // 0x100003a0c
        int64_t v20 = v19 % 2 == 0 ? (int64_t)&g111 : (int64_t)&g100; // 0x100003a14
        *(int64_t *)(v2 - 8) = v20;
        *(int64_t *)(v2 - 16) = *(int64_t *)*v11;
        _printf(g58);
        *v12 = *(char *)*v4;
        *v7 = 0x2435bbd3;
        *(char *)(v3 - 33) = *v12 % 2;
        *v7 = 0x6d12904f;
        v15 = _sleep(2);
        *v7 = -0x91ef592;
        *v13 = *(int32_t *)*v8;
        *v7 = -0x239a5ae4;
        *v14 = *v13 + 1;
        *v7 = -0x29c2b82e;
        *(int32_t *)*v8 = *v14;
        *v7 = -0xf55d006;
        *v9 = *(int32_t *)*v8;
        *v7 = 0x783ec9c8;
        *v10 = *(int32_t *)*v5;
        *v7 = 0x6f19b2c;
        v16 = *v9;
        v17 = *v10;
        v18 = v16 - v17;
        *v7 = v18 < 0 == ((v18 ^ v16) & (v17 ^ v16)) < 0 ? 0x75d96b31 : -0x7d5f3e16;
    }
    int64_t * v21 = (int64_t *)(v3 - 24); // 0x100003c40
    *v21 = (int64_t)&g148;
    *v7 = -0x7a946986;
    int64_t result = _puts(*v21); // 0x100003c58
    *v7 = 0x10f25a20;
    return result;
}

