//
// The middle source was generated by the Retargetable Decompiler
// Website: https://retdec.com
//
// The final source was generated by the UraniumVCPU Sampler Framework
// Website: http://yunyoo.cn
//

// Address range: 0x7d4 - 0x7dc
// Demangled:     do_main(int, char const**)
int32_t _Z7do_mainiPPKc(int32_t result, char ** a2) {
    __asm_svcge(0x3b5f0);
    bool v1; // 0x7d4
    if (v1) {
        // branch -> 
    }
    return result;
}

// Address range: 0x7dc - 0x1266
int32_t sub_7dc(int32_t a1, int32_t a2) {
    // 0x7dc
    int32_t v1; // 0x7dc
    *(int32_t *)(v1 - 28) = *(int32_t *)g3;
    int32_t * v2 = (int32_t *)(v1 - 88); // 0x7fc
    *v2 = -0x7e757bbe;
    int32_t * v3 = (int32_t *)(v1 - 92); // 0x808
    *v3 = 0x1f9f58a6;
    int32_t v4 = *v2; // 0x812
    if (v4 != -0x54cef45b) {
        __asm_itt();
    }
    int32_t v5 = v4 == -0x54cef45b ? -0x7c60d859 : -0x32dabfc9;
    *v3 = v5;
    *(int32_t *)(v1 - 84) = __asm_dmb(g180, -0x54cef45b, v5, v1);
    char * v6 = (char *)(v1 - 78); // 0x888
    *v6 = 0;
    *v3 = 0x7b00436c;
    if (*v6 != 0) {
        __asm_itt();
    }
    *(char *)&g102 = g99 ^ 127;
    g103 = g100 ^ -19;
    g104[0] = g101 ^ 25;
    g105[0] = g99 ^ -7;
    g106[0] = g100 ^ 8;
    g113[0] = g107 ^ 81;
    char * v7 = (char *)(v1 - 77); // 0x94c
    *v7 = g108;
    *v3 = -0x7ac2d12e;
    char v8 = *v7;
    g112 = v8;
    g113[0] = g109 ^ 67;
    g114[0] = g110 ^ 48;
    g115[0] = g111 ^ 82;
    g116[0] = v8 ^ -27;
    g147[0] = g117 ^ 13;
    g148[0] = g118 ^ -61;
    g149[0] = g119 ^ -11;
    g150[0] = g120 ^ 96;
    g151[0] = g121 ^ -56;
    g152[0] = g122 ^ 104;
    g153[0] = g123 ^ -30;
    g154[0] = g124 ^ 11;
    g155[0] = g125 ^ 79;
    g156[0] = g126 ^ -24;
    g157[0] = g127 ^ 60;
    g158[0] = g128 ^ 107;
    *v3 = -0x43b280b5;
    g159[0] = g127 ^ -104;
    g160[0] = g128 ^ -90;
    g161[0] = g129 ^ -67;
    g162[0] = g130 ^ -38;
    g163[0] = g131 ^ -85;
    g164[0] = g132 ^ -102;
    g165[0] = g133 ^ 114;
    g166[0] = g134 ^ -70;
    g167[0] = g135 ^ -22;
    g168[0] = g136 ^ 102;
    g169[0] = g137 ^ 8;
    g170[0] = g138 ^ 16;
    g171[0] = g139 ^ -4;
    g172[0] = g140 ^ -114;
    g173[0] = g141 ^ -97;
    g174[0] = g142 ^ -18;
    g175[0] = g143 ^ 34;
    g176[0] = g144 ^ 23;
    *(char *)&g177 = g145 ^ 113;
    *(char *)&g178 = g146 ^ -89;
    g62[0] = g25 ^ -98;
    g63[0] = g26 ^ -5;
    g64[0] = g27 ^ 77;
    g65[0] = g28 ^ 47;
    g66[0] = g29 ^ -57;
    g67[0] = g30 ^ 93;
    g68[0] = g31 ^ 19;
    g69[0] = g32 ^ 120;
    g70[0] = g33 ^ -101;
    g71[0] = g34 ^ 70;
    g72[0] = g35 ^ 43;
    g73[0] = g36 ^ -109;
    g74[0] = g37 ^ 1;
    g75[0] = g38 ^ -77;
    g76[0] = g39 ^ -55;
    g77[0] = g40 ^ -125;
    g78[0] = g41 ^ 63;
    g79[0] = g42 ^ 116;
    g80[0] = -1 - g43;
    g81[0] = g44 ^ -28;
    g82[0] = g45 ^ -64;
    g83[0] = g46 ^ -47;
    g84[0] = g47 ^ 126;
    g85[0] = g48 ^ 21;
    g86[0] = g49 ^ -23;
    g87[0] = g50 ^ -60;
    g88[0] = g51 ^ -9;
    g89[0] = g52 ^ -9;
    g90[0] = g53 ^ -32;
    g91[0] = g54 ^ -115;
    g92[0] = g55 ^ 74;
    g93[0] = g56 ^ -127;
    g94[0] = g57 ^ 89;
    g95[0] = g58 ^ 99;
    g96[0] = g59 ^ 5;
    *(char *)&g97 = g60 ^ 73;
    *(char *)&g98 = g61 ^ 5;
    *(char *)&g14 = g4 ^ -81;
    *(char *)&g15 = *(char *)0x6fff ^ 2;
    *(char *)&g16 = g5 ^ -127;
    g17[0] = g6 ^ 116;
    g18[0] = g7 ^ -18;
    g19[0] = g8 ^ 5;
    g20[0] = g9 ^ 54;
    g21[0] = g10 ^ -26;
    g22[0] = g11 ^ 13;
    int32_t v9 = g12; // 0xe14
    int32_t v10 = v9 & 51 ^ 51; // 0xe18
    int32_t v11 = v10 | v9 & 204; // 0xe1e
    g23[0] = v11;
    *(char *)&g24 = g13 ^ 96;
    *v3 = 0xddbac8;
    __asm_dmb(0xddbac8, (int32_t)&g14, v11, v10);
    g179 = 1;
    int32_t * v12 = (int32_t *)(v1 - 76); // 0xe62
    int32_t v13; // bp-80, 0x7dc
    *v12 = (int32_t)&v13;
    *v3 = 0x3b7bd90e;
    int32_t * v14 = (int32_t *)(v1 - 72); // 0xe9c
    int32_t v15; // bp-88, 0x7dc
    *v14 = (int32_t)&v15;
    int32_t * v16 = (int32_t *)(v1 - 68); // 0xea6
    int32_t v17; // bp-96, 0x7dc
    *v16 = (int32_t)&v17;
    int32_t * v18 = (int32_t *)(v1 - 64); // 0xeb0
    int32_t v19; // bp-104, 0x7dc
    *v18 = (int32_t)&v19;
    *(int32_t *)*v12 = a1;
    *v3 = (int32_t)&g1 | 0x72d80000;
    *(int32_t *)*v14 = a2;
    if (getenv(&g16) != 0) {
        __asm_itt();
    }
    *v3 = -0x708a2554;
    _ZL10anti_debugv();
    *v3 = 0xe14b2a2;
    *(int32_t *)*v16 = 0;
    int32_t * v20 = (int32_t *)(v1 - 60); // 0xf8c
    int32_t * v21 = (int32_t *)(v1 - 56); // 0xfb6
    char * v22 = (char *)(v1 - 49);
    int32_t * v23 = (int32_t *)(v1 - 48);
    int32_t * v24 = (int32_t *)(v1 - 44);
    int32_t * v25 = (int32_t *)(v1 - 40);
    int32_t * v26 = (int32_t *)(v1 - 36);
    *v3 = (int32_t)&g2 | -0x2ffe0000;
    *v20 = *(int32_t *)*v16;
    *v3 = -0x12e2ec6;
    *v21 = *(int32_t *)*v12;
    *v3 = 0x5a48b80d;
    int32_t v27 = *v20; // 0xfda
    int32_t v28 = *v21; // 0xfde
    if (v27 < v28) {
        __asm_it();
    }
    *v22 = (char)(v27 < v28);
    *v3 = 0x11fc151b;
    while (*v22 != 0) {
        // 0x101e
        __asm_itt();
        *v3 = 0x72f3addc;
        *(char *)*v18 = (char)_ZL19am_I_being_debuggedv();
        *v23 = *(int32_t *)*(int32_t *)*v14;
        unsigned char v29 = *(char *)*v18; // 0x1038
        if (v29 % 2 != 0) {
            __asm_it();
        }
        int32_t v30 = v29 % 2 == 0 ? (int32_t)&g111 : (int32_t)&g102;
        *v24 = v30;
        *v3 = 0x5d546d85;
        printf(g62, *v23, *v24);
        *v3 = -0x2e3fbeec;
        if (*(char *)*v18 % 2 != 0) {
            __asm_itt();
        }
        *v3 = 0x7cece9f;
        sleep(2);
        *v3 = 0x33833e5f;
        *v25 = *(int32_t *)*v16;
        *v3 = 0x696d198f;
        *v26 = *v25 + 1;
        *v3 = -0x66db3d05;
        *(int32_t *)*v16 = *v26;
        *v3 = (int32_t)&g2 | -0x2ffe0000;
        *v20 = *(int32_t *)*v16;
        *v3 = -0x12e2ec6;
        *v21 = *(int32_t *)*v12;
        *v3 = 0x5a48b80d;
        v27 = *v20;
        v28 = *v21;
        if (v27 < v28) {
            __asm_it();
        }
        *v22 = (char)(v27 < v28);
        *v3 = 0x11fc151b;
    }
    int32_t * v31 = (int32_t *)(v1 - 32); // 0x11f2
    *v31 = (int32_t)&g147;
    *v3 = 0x21398fe1;
    puts(*v31);
    *v3 = -0x7a8b3ca6;
    return 0;
}

