//
// The middle source was generated by the Retargetable Decompiler
// Website: https://retdec.com
//
// The final source was generated by the UraniumVCPU Sampler Framework
// Website: http://yunyoo.cn
//

// Address range: 0x994 - 0x1bd8
// Demangled:     do_main(int, char const**)
int64_t _Z7do_mainiPPKc(int32_t a1, char ** a2) {
    // 0x994
    int64_t v1; // 0x994
    __asm_mrs(v1, v1);
    g101[0] = *(char *)&g97 ^ -94;
    g102[0] = *(char *)&g98 ^ 87;
    g103[0] = *(char *)&g99 ^ -127;
    *(char *)&g104 = 101;
    *(char *)&g105 = *(char *)&g100 ^ 90;
    g112[0] = *(char *)&g106 ^ 16;
    g113[0] = *(char *)&g107 ^ 57;
    g114[0] = *(char *)&g108 ^ 61;
    g115[0] = *(char *)&g109 ^ -61;
    *(char *)&g116 = *(char *)&g110 ^ -29;
    *(char *)&g117 = *(char *)&g111 ^ -113;
    g147[0] = *(char *)&g118 ^ 8;
    g148[0] = *(char *)&g119 ^ -125;
    g149[0] = *(char *)&g120 ^ -78;
    g150[0] = *(char *)&g121 ^ 16;
    g151[0] = *(char *)&g122 ^ -81;
    g152[0] = *(char *)&g123 ^ -34;
    g153[0] = *(char *)&g124 ^ -43;
    g154[0] = *(char *)&g125 ^ -52;
    g155[0] = *(char *)&g126 ^ 126;
    g156[0] = *(char *)&g127 ^ 31;
    g157[0] = *(char *)&g128 ^ -118;
    g158[0] = *(char *)&g129 ^ 46;
    g159[0] = *(char *)&g130 ^ -18;
    g160[0] = *(char *)&g131 ^ 110;
    g161[0] = *(char *)&g132 ^ 45;
    g162[0] = *(char *)&g133 ^ -35;
    g163[0] = *(char *)&g134 ^ -111;
    g164[0] = *(char *)&g135 ^ 73;
    g165[0] = *(char *)&g136 ^ 109;
    g166[0] = *(char *)&g137 ^ 71;
    g167[0] = *(char *)&g138 ^ -22;
    g168[0] = *(char *)&g139 ^ 71;
    g169[0] = *(char *)&g140 ^ 48;
    g170[0] = *(char *)&g141 ^ -14;
    g171[0] = *(char *)&g142 ^ 18;
    g172[0] = *(char *)&g143 ^ -82;
    g173[0] = *(char *)&g144 ^ -93;
    g174[0] = *(char *)&g145 ^ -44;
    g175[0] = *(char *)&g146 ^ -33;
    g176[0] = 111;
    *(char *)&g177 = 126;
    *(char *)&g178 = 0;
    g12[0] = *(char *)&g1 ^ 91;
    g13[0] = *(char *)&g2 ^ -8;
    g14[0] = *(char *)&g3 ^ 43;
    g15[0] = *(char *)&g4 ^ -34;
    g16[0] = *(char *)&g5 ^ -37;
    g17[0] = *(char *)&g6 ^ 39;
    g18[0] = *(char *)&g7 ^ -74;
    g19[0] = *(char *)&g8 ^ 7;
    *(char *)&g20 = *(char *)&g9 ^ -96;
    *(char *)&g21 = *(char *)&g10 ^ 64;
    *(char *)&g22 = *(char *)&g11 ^ 27;
    g60[0] = *(char *)&g23 ^ 55;
    g61[0] = *(char *)&g24 ^ 26;
    g62[0] = *(char *)&g25 ^ -64;
    g63[0] = *(char *)&g26 ^ -122;
    g64[0] = *(char *)&g27 ^ 95;
    g65[0] = *(char *)&g28 ^ -51;
    g66[0] = *(char *)&g29 ^ -118;
    g67[0] = *(char *)&g30 ^ 102;
    g68[0] = *(char *)&g31 ^ -93;
    g69[0] = *(char *)&g32 ^ 6;
    g70[0] = *(char *)&g33 ^ 5;
    g71[0] = *(char *)&g34 ^ -84;
    g72[0] = *(char *)&g35 ^ -126;
    g73[0] = *(char *)&g36 ^ 87;
    g74[0] = *(char *)&g37 ^ 20;
    g75[0] = *(char *)&g38 ^ -58;
    g76[0] = *(char *)&g39 ^ -8;
    g77[0] = *(char *)&g40 ^ -9;
    g78[0] = *(char *)&g41 ^ 63;
    g79[0] = *(char *)&g42 ^ -68;
    g80[0] = *(char *)&g43 ^ -71;
    g81[0] = *(char *)&g44 ^ 56;
    g82[0] = *(char *)&g45 ^ -104;
    g83[0] = *(char *)&g46 ^ -82;
    g84[0] = *(char *)&g47 ^ 1;
    g85[0] = *(char *)&g48 ^ 115;
    g86[0] = *(char *)&g49 ^ -76;
    g87[0] = *(char *)&g50 ^ 45;
    g88[0] = *(char *)&g51 ^ -42;
    g89[0] = *(char *)&g52 ^ -125;
    g90[0] = *(char *)&g53 ^ -81;
    g91[0] = *(char *)&g54 ^ 14;
    g92[0] = *(char *)&g55 ^ 105;
    g93[0] = *(char *)&g56 ^ 53;
    g94[0] = *(char *)&g57 ^ 68;
    *(char *)&g95 = *(char *)&g58 ^ 9;
    *(char *)&g96 = *(char *)&g59 ^ -104;
    __asm_stlr(1, g179);
    int64_t v2 = _ZL10anti_debugv((int64_t *)getenv(g12)); // 0x1870
    while (true) {
        uint64_t v3 = _ZL19am_I_being_debuggedv((int64_t *)v2); // 0x1954
        int64_t v4 = v3 % 2 == 0 ? (int64_t)&g112 : (int64_t)&g101; // 0x1a00
        printf(g60, *(int64_t *)v1, v4);
        v2 = sleep(2);
    }
}

