//
// The middle source was generated by the Retargetable Decompiler
// Website: https://retdec.com
//
// The final source was generated by the UraniumVCPU Sampler Framework
// Website: http://yunyoo.cn
//

// Address range: 0x1000066bc - 0x10000793c
// Demangled:     do_main(int, char const**)
int64_t __Z7do_mainiPPKc(int32_t a1, char ** a2) {
    // 0x1000066bc
    g106[0] = *(char *)&g102 ^ -57;
    g107[0] = *(char *)&g103 ^ -71;
    g108[0] = *(char *)&g104 ^ -3;
    g109[0] = *(char *)&g105 ^ 108;
    *(char *)&g110 = 101;
    *(char *)&g111 = 0;
    g9[0] = *(char *)&g1 ^ 126;
    g10[0] = *(char *)&g2 ^ -117;
    g11[0] = *(char *)&g3 ^ -47;
    g12[0] = *(char *)&g4 ^ 90;
    g13[0] = *(char *)&g5 ^ -106;
    g14[0] = *(char *)&g6 ^ -66;
    g15[0] = *(char *)&g7 ^ 124;
    g16[0] = *(char *)&g8 ^ -47;
    g17[0] = 66;
    *(char *)&g18 = 71;
    *(char *)&g19 = 0;
    g144[0] = *(char *)&g112 ^ -105;
    g145[0] = *(char *)&g113 ^ 83;
    g146[0] = *(char *)&g114 ^ 127;
    g147[0] = *(char *)&g115 ^ 102;
    g148[0] = *(char *)&g116 ^ -16;
    g149[0] = *(char *)&g117 ^ -98;
    g150[0] = *(char *)&g118 ^ -106;
    g151[0] = *(char *)&g119 ^ -83;
    g152[0] = *(char *)&g120 ^ -70;
    g153[0] = *(char *)&g121 ^ -47;
    g154[0] = *(char *)&g122 ^ -49;
    g155[0] = *(char *)&g123 ^ -18;
    g156[0] = *(char *)&g124 ^ -4;
    g157[0] = *(char *)&g125 ^ -5;
    g158[0] = *(char *)&g126 ^ 30;
    g159[0] = *(char *)&g127 ^ -5;
    g160[0] = *(char *)&g128 ^ 50;
    g161[0] = *(char *)&g129 ^ -105;
    g162[0] = *(char *)&g130 ^ 28;
    g163[0] = *(char *)&g131 ^ 28;
    g164[0] = *(char *)&g132 ^ 34;
    g165[0] = *(char *)&g133 ^ 61;
    g166[0] = *(char *)&g134 ^ 41;
    g167[0] = *(char *)&g135 ^ 107;
    g168[0] = *(char *)&g136 ^ -85;
    g169[0] = *(char *)&g137 ^ -69;
    g170[0] = *(char *)&g138 ^ -15;
    g171[0] = *(char *)&g139 ^ 85;
    g172[0] = *(char *)&g140 ^ -20;
    g173[0] = *(char *)&g141 ^ -106;
    *(char *)&g174 = *(char *)&g142 ^ 91;
    *(char *)&g175 = *(char *)&g143 ^ -87;
    g57[0] = *(char *)&g20 ^ -94;
    g58[0] = *(char *)&g21 ^ 95;
    g59[0] = *(char *)&g22 ^ -26;
    g60[0] = *(char *)&g23 ^ 76;
    g61[0] = *(char *)&g24 ^ 30;
    g62[0] = *(char *)&g25 ^ -58;
    g63[0] = *(char *)&g26 ^ -111;
    g64[0] = *(char *)&g27 ^ 34;
    g65[0] = *(char *)&g28 ^ -127;
    g66[0] = *(char *)&g29 ^ 60;
    g67[0] = *(char *)&g30 ^ -86;
    g68[0] = *(char *)&g31 ^ -42;
    g69[0] = *(char *)&g32 ^ 64;
    g70[0] = *(char *)&g33 ^ 125;
    g71[0] = *(char *)&g34 ^ 117;
    g72[0] = *(char *)&g35 ^ 79;
    g73[0] = *(char *)&g36 ^ -14;
    g74[0] = *(char *)&g37 ^ -62;
    g75[0] = *(char *)&g38 ^ -4;
    g76[0] = -1 - *(char *)&g39;
    g77[0] = *(char *)&g40 ^ 101;
    g78[0] = *(char *)&g41 ^ -23;
    g79[0] = *(char *)&g42 ^ -65;
    g80[0] = *(char *)&g43 ^ -14;
    g81[0] = *(char *)&g44 ^ 48;
    g82[0] = *(char *)&g45 ^ 13;
    g83[0] = *(char *)&g46 ^ -93;
    g84[0] = *(char *)&g47 ^ 24;
    g85[0] = *(char *)&g48 ^ 127;
    g86[0] = *(char *)&g49 ^ 61;
    g87[0] = *(char *)&g50 ^ 87;
    g88[0] = *(char *)&g51 ^ 65;
    g89[0] = *(char *)&g52 ^ -16;
    g90[0] = *(char *)&g53 ^ -22;
    g91[0] = *(char *)&g54 ^ 72;
    *(char *)&g92 = *(char *)&g55 ^ 81;
    *(char *)&g93 = *(char *)&g56 ^ -101;
    g97[0] = *(char *)&g94 ^ -123;
    g98[0] = *(char *)&g95 ^ 54;
    g99[0] = *(char *)&g96 ^ -47;
    *(char *)&g100 = 101;
    *(char *)&g101 = 0;
    __asm_stlr(1, g176);
    int64_t v1; // bp-184, 0x1000066bc
    int64_t v2 = &v1; // 0x100007494
    _getenv(g9);
    int64_t v3 = __ZL10anti_debugv(); // 0x100007568
    int64_t v4; // bp-168, 0x1000066bc
    *(int32_t *)&v4 = 0;
    int64_t v5 = v3; // 0x100007620
    while (true) {
        unsigned char v6 = (char)__ZL19am_I_being_debuggedv((int64_t *)v5) % 2; // 0x1000076f0
        *(char *)&v1 = v6;
        int64_t v7 = v6 == 0 ? (int64_t)&g106 : (int64_t)&g97; // 0x100007714
        *(int64_t *)(v2 - 8) = v7;
        int64_t v8; // 0x1000066bc
        *(int64_t *)(v2 - 16) = *(int64_t *)v8;
        _printf(g57);
        v5 = _sleep(2);
        *(int32_t *)&v4 = *(int32_t *)&v4 + 1;
    }
}

